### ISSUE TITLE
ggplot2 is switching to `scales::Range` classes

### ISSUE THREAD

**Issue by teunbrand** [const-ae/gggroupedscale#1]
Hi Constantin,

Funny that I found your repo that we discussed during the conference in this way :)

In any case, I have come to warn you that the unexported range constructors from ggplot2 are being superseded by the exported {scales} versions. Here is an example where you're using these:

https://github.com/const-ae/gggroupedscale/blob/15136443f6141fd05bce671cb18fb8289873e407/R/scale-discrete-grouped.R#L160-L161

If you replace these constructors with `scales::ContinuousRange$new()` and `scales::DiscreteRange$new()`, all should sync up with the impending dev version of ggplot2. For more context, see https://github.com/tidyverse/ggplot2/pull/5086.

Cheers!

**Comment by const-ae** [comment]
Oh that's cool. Does `scales::ContinuousRange$new()` work only with the dev version? I.e., should I add a version check for ggplot to avoid breaking the compatibility if an older ggplot version is installed?

Anyways, I wrote the package for a specific plot I needed repeatedly in a paper and knew it was very fragile. Any chance you would add the increased distance between groups to one of your packages? I would be happy to abandon this hack of a package 😅

**Comment by teunbrand** [comment]
Yeah that sounds like something that could fit in ggh4x. I've opened https://github.com/teunbrand/ggh4x/issues/94, but I have no idea when I'll get around to implementing anything 😅

**Comment by const-ae** [comment]
That's great, and I very much feel you on the prioritization question 😄

**Comment by teunbrand** [comment]
I'll close this here, unless you still plan on switching range classes :)
